name: gitConfig
description: "Sets git username/email and push behavior"
runs:
  using: composite
  steps:
    - run: git config --global push.default current
      shell: bash
    - run: git config --global user.email juicyjusung@gmail.com
      shell: bash
    - run: git config --global user.name juicyjusung-bot
      shell: bash
